### ISSUE TITLE
hash2properties PR

### ISSUE THREAD

**Issue by droopy4096** [mmckinst/puppet-hash2stuff#18]
I found hash2stuff very useful however I was missing Java properties file management, so I've added one: PR #17 

One of the tests fails (puppet 4.0) but it fails across the board so it either needs to be dropped or refactored (or just let me know what could be done on my end to get PR accepted).

**Comment by mmckinst** [comment]
I've commented on the PR. I think your code should work as is but can you squash the commits?

**Comment by mmckinst** [comment]
Thank you very much for the PR! Sorry for the long delay in getting it meregd.
